package io.github.akaryc1b.approval.connector.dingtalk.token;

import java.util.Locale;

public enum DingTalkTokenFailure {
    NONE,
    DISABLED,
    PRODUCTION_NOT_AUTHORIZED,
    KILL_SWITCH_DISABLED,
    KILL_SWITCH_REVISION_DRIFT,
    ROUTE_REVALIDATION_FAILED,
    TENANT_MISMATCH,
    PROVIDER_MISMATCH,
    ROUTE_PLAN_INVALID,
    CREDENTIAL_NOT_FOUND,
    CREDENTIAL_DISABLED,
    CREDENTIAL_REVOKED,
    CREDENTIAL_EXPIRED,
    CREDENTIAL_NOT_YET_VALID,
    CREDENTIAL_ROTATION_PENDING,
    CREDENTIAL_VERSION_DRIFT,
    CREDENTIAL_BINDING_DRIFT,
    CREDENTIAL_POLICY_DRIFT,
    CREDENTIAL_MATERIAL_FAILURE,
    ENDPOINT_UNAVAILABLE,
    ENDPOINT_TIMEOUT,
    ENDPOINT_CANCELLED,
    ENDPOINT_MALFORMED,
    TOKEN_EXPIRED,
    TOKEN_LIFETIME_INVALID,
    CACHE_CAPACITY_EXCEEDED,
    SINGLE_FLIGHT_TIMEOUT,
    SINGLE_FLIGHT_FAILED,
    LEASE_CLOSED,
    CONCURRENT_ACCESS_REJECTED,
    COORDINATOR_CLOSED,
    UNKNOWN;

    public String stableCode() {
        return name().toLowerCase(Locale.ROOT);
    }
}
