package io.github.akaryc1b.approval.application;

import io.github.akaryc1b.approval.application.port.ApprovalMigrationAttemptClaimStore;
import io.github.akaryc1b.approval.application.port.ApprovalMigrationAttemptClaimStore.ClaimRequest;
import io.github.akaryc1b.approval.application.port.ApprovalMigrationAttemptClaimStore.ClaimResult;
import io.github.akaryc1b.approval.application.port.ApprovalMigrationAttemptClaimStore.RenewalRequest;
import io.github.akaryc1b.approval.application.port.ApprovalMigrationAttemptClaimStore.RenewalResult;
import io.github.akaryc1b.approval.application.port.ApprovalMigrationAttemptProvisioningStore;
import io.github.akaryc1b.approval.application.port.ApprovalMigrationAttemptProvisioningStore.ProvisioningRequest;

import java.time.Clock;
import java.time.Duration;
import java.time.Instant;
import java.util.Objects;
import java.util.UUID;
import java.util.function.Supplier;

/** Internal bounded claim service; worker identity is generated by the server. */
public final class ApprovalMigrationAttemptClaimService {

    private final ApprovalMigrationAttemptProvisioningStore provisioning;
    private final ApprovalMigrationAttemptClaimStore claims;
    private final ApprovalReleasePackageHasher hasher;
    private final Clock clock;
    private final Supplier<String> workerIdentity;
    private final Duration leaseDuration;

    public ApprovalMigrationAttemptClaimService(
        ApprovalMigrationAttemptProvisioningStore provisioning,
        ApprovalMigrationAttemptClaimStore claims,
        ApprovalReleasePackageHasher hasher,
        Clock clock,
        Supplier<String> workerIdentity,
        Duration leaseDuration
    ) {
        this.provisioning = Objects.requireNonNull(
            provisioning,
            "provisioning must not be null"
        );
        this.claims = Objects.requireNonNull(claims, "claims must not be null");
        this.hasher = Objects.requireNonNull(hasher, "hasher must not be null");
        this.clock = Objects.requireNonNull(clock, "clock must not be null");
        this.workerIdentity = Objects.requireNonNull(
            workerIdentity,
            "workerIdentity must not be null"
        );
        this.leaseDuration = requirePositive(leaseDuration);
    }

    public ClaimResult claim(ClaimCommand command) {
        Objects.requireNonNull(command, "command must not be null");
        String workerId = requireText(workerIdentity.get(), "worker identity", 200);
        Instant now = clock.instant();
        String requestHash = hasher.hashValues(
            "M5-D2-BOUNDED-CLAIM-V1",
            command.tenantId(),
            command.intentId(),
            command.limit(),
            workerId,
            command.requestId(),
            command.traceId()
        );
        provisioning.ensureInitialAttempts(new ProvisioningRequest(
            command.tenantId(),
            command.intentId(),
            workerId,
            now,
            command.requestId(),
            command.traceId(),
            requestHash
        ));
        return claims.claim(new ClaimRequest(
            command.tenantId(),
            command.intentId(),
            workerId,
            command.limit(),
            now,
            now.plus(leaseDuration),
            command.requestId(),
            command.traceId(),
            requestHash
        ));
    }

    public RenewalResult renew(RenewalCommand command) {
        Objects.requireNonNull(command, "command must not be null");
        String workerId = requireText(workerIdentity.get(), "worker identity", 200);
        Instant now = clock.instant();
        return claims.renew(new RenewalRequest(
            command.tenantId(),
            command.attemptId(),
            workerId,
            now,
            now.plus(leaseDuration),
            command.requestId(),
            command.traceId()
        ));
    }

    public record ClaimCommand(
        String tenantId,
        UUID intentId,
        int limit,
        String requestId,
        String traceId
    ) {
        public ClaimCommand {
            tenantId = requireText(tenantId, "tenantId", 128);
            intentId = Objects.requireNonNull(intentId, "intentId must not be null");
            if (limit < 1 || limit > 100) {
                throw new IllegalArgumentException("limit must be between 1 and 100");
            }
            requestId = requireText(requestId, "requestId", 128);
            traceId = optionalText(traceId, 256);
        }
    }

    public record RenewalCommand(
        String tenantId,
        UUID attemptId,
        String requestId,
        String traceId
    ) {
        public RenewalCommand {
            tenantId = requireText(tenantId, "tenantId", 128);
            attemptId = Objects.requireNonNull(attemptId, "attemptId must not be null");
            requestId = requireText(requestId, "requestId", 128);
            traceId = optionalText(traceId, 256);
        }
    }

    private static Duration requirePositive(Duration value) {
        Objects.requireNonNull(value, "leaseDuration must not be null");
        if (value.isZero() || value.isNegative() || value.compareTo(Duration.ofMinutes(15)) > 0) {
            throw new IllegalArgumentException(
                "leaseDuration must be positive and no greater than 15 minutes"
            );
        }
        return value;
    }

    private static String optionalText(String value, int maximum) {
        return value == null || value.isBlank() ? null : requireText(value, "traceId", maximum);
    }

    private static String requireText(String value, String name, int maximum) {
        Objects.requireNonNull(value, name + " must not be null");
        String normalized = value.trim();
        if (normalized.isEmpty() || normalized.length() > maximum) {
            throw new IllegalArgumentException(name + " is blank or exceeds maximum length " + maximum);
        }
        return normalized;
    }
}
